version: "3.9"
services:
  # instant-ngp:
  #   build:
  #     context: .
  #     dockerfile: docker/instant-ngp/instant-ngp.Dockerfile
  #   image: vip-nerf/instant-ngp-gui-test

  #   stdin_open: true
  #   tty: true

  #   environment:
  #     NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics

  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ./src/instant-ngp:/home/docker/instant-ngp
  #     - /tmp/.X11-unix:/tmp/.X11-unix

  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
  #           capabilities: [gpu]

  # kilonerf:
  #   build:
  #     context: .
  #     dockerfile: docker/kilonerf/kilonerf.Dockerfile
  #   image: vip-nerf/kilonerf

  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ./src/kilonerf:/home/docker/kilonerf
  #     - /pub1/${USERNAME}/data/kilonerf_nsvf:/home/docker/kilonerf/data/nsvf
  #   ipc: host
  #   tty: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
  #           capabilities: [gpu]

  nerf-pytorch-10:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_10.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  nerf-pytorch-09:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_09.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  nerf-pytorch-08:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_08.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  nerf-pytorch-07:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_07.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  nerf-pytorch-06:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_06.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  nerf-pytorch-05:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_05.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  nerf-pytorch-04:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_04.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  nerf-pytorch-03:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_03.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  nerf-pytorch-02:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_02.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  nerf-pytorch-01:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_01.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  nerf-pytorch-005:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/fern_configs/fern_005.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]
            

# # ===============================================================================================

#   nerf-pytorch-trex-10:
#     build:
#       context: .
#       dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
#       args:
#         USER_WANDB_MODE: ${WANDB_MODE:-offline}
#         USER_WANDB_KEY: ${WANDB_KEY:-}

#     image: vip-nerf/nerf-pytorch

#     user: ${FIXUID:?}:${FIXGID:?}
#     volumes:
#       - ./src/nerf-pytorch:/home/docker/nerf-pytorch
#     ipc: host
#     tty: true
#     command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_10.txt"]
#     deploy:
#       resources:
#         reservations:
#           devices:
#           - driver: nvidia
#             device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
#             capabilities: [gpu]

#   nerf-pytorch-trex-09:
#     build:
#       context: .
#       dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
#       args:
#         USER_WANDB_MODE: ${WANDB_MODE:-offline}
#         USER_WANDB_KEY: ${WANDB_KEY:-}

#     image: vip-nerf/nerf-pytorch

#     user: ${FIXUID:?}:${FIXGID:?}
#     volumes:
#       - ./src/nerf-pytorch:/home/docker/nerf-pytorch
#     ipc: host
#     tty: true
#     command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_09.txt"]
#     deploy:
#       resources:
#         reservations:
#           devices:
#           - driver: nvidia
#             device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
#             capabilities: [gpu]

  # nerf-pytorch-trex-08:
  #   build:
  #     context: .
  #     dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
  #     args:
  #       USER_WANDB_MODE: ${WANDB_MODE:-offline}
  #       USER_WANDB_KEY: ${WANDB_KEY:-}

  #   image: vip-nerf/nerf-pytorch

  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ./src/nerf-pytorch:/home/docker/nerf-pytorch
  #   ipc: host
  #   tty: true
  #   command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_08.txt"]
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
  #           capabilities: [gpu]

#   nerf-pytorch-trex-07:
#     build:
#       context: .
#       dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
#       args:
#         USER_WANDB_MODE: ${WANDB_MODE:-offline}
#         USER_WANDB_KEY: ${WANDB_KEY:-}

#     image: vip-nerf/nerf-pytorch

#     user: ${FIXUID:?}:${FIXGID:?}
#     volumes:
#       - ./src/nerf-pytorch:/home/docker/nerf-pytorch
#     ipc: host
#     tty: true
#     command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_07.txt"]
#     deploy:
#       resources:
#         reservations:
#           devices:
#           - driver: nvidia
#             device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
#             capabilities: [gpu]

  # nerf-pytorch-trex-06:
  #   build:
  #     context: .
  #     dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
  #     args:
  #       USER_WANDB_MODE: ${WANDB_MODE:-offline}
  #       USER_WANDB_KEY: ${WANDB_KEY:-}

  #   image: vip-nerf/nerf-pytorch

  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ./src/nerf-pytorch:/home/docker/nerf-pytorch
  #   ipc: host
  #   tty: true
  #   command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_06.txt"]
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
  #           capabilities: [gpu]

  nerf-pytorch-trex-05:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_05.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  # nerf-pytorch-trex-04:
  #   build:
  #     context: .
  #     dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
  #     args:
  #       USER_WANDB_MODE: ${WANDB_MODE:-offline}
  #       USER_WANDB_KEY: ${WANDB_KEY:-}

  #   image: vip-nerf/nerf-pytorch

  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ./src/nerf-pytorch:/home/docker/nerf-pytorch
  #   ipc: host
  #   tty: true
  #   command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_04.txt"]
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
  #           capabilities: [gpu]

  nerf-pytorch-trex-03:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_03.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

#   nerf-pytorch-trex-02:
#     build:
#       context: .
#       dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
#       args:
#         USER_WANDB_MODE: ${WANDB_MODE:-offline}
#         USER_WANDB_KEY: ${WANDB_KEY:-}

#     image: vip-nerf/nerf-pytorch

#     user: ${FIXUID:?}:${FIXGID:?}
#     volumes:
#       - ./src/nerf-pytorch:/home/docker/nerf-pytorch
#     ipc: host
#     tty: true
#     command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_02.txt"]
#     deploy:
#       resources:
#         reservations:
#           devices:
#           - driver: nvidia
#             device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
#             capabilities: [gpu]

  nerf-pytorch-trex-01:
    build:
      context: .
      dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
      args:
        USER_WANDB_MODE: ${WANDB_MODE:-offline}
        USER_WANDB_KEY: ${WANDB_KEY:-}

    image: vip-nerf/nerf-pytorch

    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/nerf-pytorch:/home/docker/nerf-pytorch
    ipc: host
    tty: true
    command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_01.txt"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

#   nerf-pytorch-trex-005:
#     build:
#       context: .
#       dockerfile: docker/nerf-pytorch/nerf-pytorch.Dockerfile
#       args:
#         USER_WANDB_MODE: ${WANDB_MODE:-offline}
#         USER_WANDB_KEY: ${WANDB_KEY:-}

#     image: vip-nerf/nerf-pytorch

#     user: ${FIXUID:?}:${FIXGID:?}
#     volumes:
#       - ./src/nerf-pytorch:/home/docker/nerf-pytorch
#     ipc: host
#     tty: true
#     command: ["python3", "run_nerf.py", "--config", "configs/trex_configs/trex_005.txt"]
#     deploy:
#       resources:
#         reservations:
#           devices:
#           - driver: nvidia
#             device_ids: ['1'] # Change to ['0', '1'] to use two GPUs
#             capabilities: [gpu]